### ISSUE TITLE
Combining at with _Just

### ISSUE THREAD

**Issue by themoritz** [joneshf/purescript-index#4]
The analogue of the following code compiles and gives me `Nothing` with the Haskell lens library:

``` purescript
module Main where

import           Data.Maybe
import qualified Data.Map as M

import Debug.Trace

import Optic.Core ((^.), (..))
import Optic.At
import Optic.Refractor.Prism (_Just)

m :: M.Map Number (M.Map Number String)
m = M.empty

deepGet :: Number -> Number -> Maybe String
deepGet x y = m ^. at x .. _Just .. at y

main = do
  trace $ deepGet 1 1
```

However, if I try to compile it with Purescript, I get the following error:

```
Error in value declaration deepGet:
No instance found for Optic.At.At u126 Prim.String u155
```

These are my dependencies:

``` json
"purescript-index": "^0.3.0",
"purescript-lens": "^0.7.0",
"purescript-refractor": "^0.4.0"
```

**Comment by joneshf** [comment]
Unfortunately, this is the compiler not inferring type classes well enough, and since we don't have fundeps or type families or anything similar, I'm not sure how to fix it.

If you annotate one of the `at` lenses with its type, it should infer the other properly.

``` purescript
deepGet' :: Number -> Number -> Maybe String
deepGet' x y = m ^. (at x :: LensP (M.Map Number (M.Map Number String)) (Maybe (M.Map Number String))) .. _Just .. at y
-- or
deepGet'' :: Number -> Number -> Maybe String
deepGet'' x y = m ^. at x .. _Just .. (at y :: LensP (M.Map Number String) (Maybe String))
```

**Comment by joneshf** [comment]
I just had a thought!

If you make a slightly less polymorphic version of `at` it should work.

``` purescript
deepGet''' :: Number -> Number -> Maybe String
deepGet''' x y = m ^. at' x .. _Just .. at' y

at' :: forall k v. (Ord k) => k -> LensP (M.Map k v) (Maybe v)
at' k = at k
```

Completely defeats the purpose of having a type class, but it's probably the least obtrusive fix.

**Comment by themoritz** [comment]
Yep, that makes sense and works fine! I also think the less polymorphic version of `at` is the preferable fix. Thanks a lot!
